# Generated by Django 4.1.1 on 2022-09-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item_orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('Receita', (('Renda de Investimentos', 'Renda de Investimentos'), ('Salario de Hermann', 'Salario de Hermann'), ('Refeicao de Hermann', 'Refeicao de Hermann'), ('Salario de Carla', 'Salario de Carla'), ('Refeicao de Carla', 'Refeicao de Carla'), ('Processo do Alphaville', 'Processo do Alphaville'))), ('Despesa', (('Financiamento Bancario', 'Financiamento Bancario'), ('Plano de Previdencia', 'Plano de Previdencia'), ('Empregada', 'Empregada'), ('NuBank Hermann', 'NuBank Hermann'), ('Nubank Carla', 'Nubank Carl'), ('Escola', 'Escola'), ('Seguro', 'Seguro'), ('Internet', 'Internet'), ('Energia Celpe', 'Energia Celpe'), ('Energia Cosern', 'Energia Cosern'), ('INSS', 'INSS'), ('Celular Hermann', 'Celular Hermann'), ('Celular Carla', 'Celular Carla'), ('Condominio Maria Borba', 'Condominio Maria Borba'), ('Condominio Alphaville', 'Condominio Alphaville'), ('IPTU+BOMB', 'IPTU+BOMB'), ('IPVA+MULTA', 'IPVA+MULTA'), ('Alimentacao', 'Alimentacao'), ('Agua/Esgoto Pipa', 'Agua/Esgoto Pipa'), ('Advogado/Outros', 'Advogado/Outros'), ('Transf. Conta Invest', 'Transf. Conta Invest')))], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
